server:
  port: 8761
spring:
  application:
    name: study-registry
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://${security.user.name}:${security.user.password}@127.0.0.1:${server.port}/eureka/
  instance:
    status-page-url: http://${spring.cloud.client.ipAddress}:${server.port}/swagger-ui.html