logging:
  level:
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://huanghongfei:135797531@127.0.0.1:8761/eureka/
management:
  security:
    enabled: false
spring:
  boot:
    admin:
      username: huanghongfei
      password: 135797531